### PR TITLE
TWIS-44/create post

### PR DESCRIPTION
**Pull request by Jack-Vu**
# TWIS-44/create-post

## Link to Story

https://re-boot.atlassian.net/browse/TWIS-44

## Description

Working on user creating a post flow with adding picture, emote and text. 

## Screenshot(s) / GIF(s):

create-post

## Type of change

- [ ] Bug fix
- [x] New feature
- [ ] Dependency / Configuration update
- [ ] Documentation update

## Checklist:

- [x] My code follows the project's style guidelines
- [x] I have created a Storybook story for my component(s)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by ShinK8245 — APPROVED** [review]

**Review by Muradil-Erkin — APPROVED** [review]

**Review by KrystalOm — COMMENTED** [review]
Screenshot 2024-03-15 at 3 49 10 PM
I'm not sure if this error is occurring locally or in the environment.

**Comment by Jack-Vu** [comment]
You'll need to delete your node modules and then do an npm i that should resolve the issue @KrystalOm

**Comment by KrystalOm** [comment]
> You'll need to delete your node modules and then do an npm i that should resolve the issue @KrystalOm

Thank you!

**Review by Tsai-Anthony — CHANGES_REQUESTED** [review]
Hi Jack 😄 
Everything pretty much meets your acceptance criteria! 
But I also noticed that users can exceed the 250 character limit by using emojis. I believe this is because each emoji is counted as 2 or 3 characters?  🤔 
image

**Review by KrystalOm — APPROVED** [review]
Screenshot 2024-03-16 at 3 34 24 AM


LGTM 👍

**Review by LenaChen7 — APPROVED** [review]
LGTM

**Review by Tsai-Anthony — APPROVED** [review]
**LGTM** 
Nice fix 😄 !!  I tested the emojis when the current character count is at 249 and 250. Overall you seemed to knocked it out! I did notice that if its at 249 count, adding a 🕳️ emoji (previously counted as 3 characters) would still push it over 250. But it does not allow the user to add anything more.
image

**Review by ShinK8245 — APPROVED** [review]
LGTM!

**Pull request merged**
