### PR TITLE
TWIS-66/sign-in-page

### PR DESCRIPTION
**Pull request by Muradil-Erkin**
# TWIS-66/sign-in-page

## Link to Story

https://re-boot.atlassian.net/browse/TWIS-66

## Description

- Fixed auth issue
- Pages are protected
- Signin page implemented

## Screenshot(s) / GIF(s):

image
## Type of change

- [ ] Bug fix
- [ ] New feature
- [ ] Dependency / Configuration update
- [ ] Documentation update

## Checklist:

- [ ] My code follows the project's style guidelines
- [ ] I have created a Storybook story for my component(s)
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by LenaChen7 — APPROVED** [review]
Looking good to me !

**Review by Karma336 — APPROVED** [review]
I checked on UI for the email log in and button functions are working

Screenshot 2024-03-14 at 7 27 18 PM

**Comment by LenaChen7** [comment]
I also noticed the color of the bottom line is little bit lighter than the one in the PR.

**Review by Karma336 — APPROVED** [review]
I checked UI for the "log in with the google" and "sign in with the email" Both the button functions are working. 
Screenshot 2024-03-14 at 7 43 18 PM

**Review by KrystalOm — APPROVED** [review]
Screenshot 2024-03-14 at 11 54 02 PM
LGTM!!
Email Sign in and Google Log in Functionality seems working well.

**Pull request merged**
